[supervisord]
nodaemon=true
user=root

; ===============================
; Laravel Serve
; ===============================
[program:laravel-serve]
command=php artisan serve --host=0.0.0.0 --port=8000
directory=/var/www
autostart=true
autorestart=true
stdout_logfile=/var/www/storage/logs/serve.log
redirect_stderr=true

; ===============================
; Laravel Queue Worker
; ===============================
[program:laravel-queue]
command=php artisan queue:work --sleep=30 --tries=3 --timeout=90
directory=/var/www
autostart=true
autorestart=true
numprocs=1
process_name=%(program_name)s_%(process_num)02d
stdout_logfile=/var/www/storage/logs/queue.log
redirect_stderr=true
stopwaitsecs=3600
