name: Electrifying Australia Website Frontend Deploy

on:
  push:
    branches: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: => Deploy Linux Server
        uses: easingthemes/ssh-deploy@v5.0.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.LINUX_SSH_KEY }}
          ARGS: "-avzr --delete"
          SOURCE: "."
          REMOTE_HOST: ${{ secrets.LINUX_HOST }}
          REMOTE_USER: ${{ secrets.LINUX_USER }}
          TARGET: "${{ secrets.LINUX_DIR_PATH }}/"

      - name: => Install required package
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.LINUX_HOST }}
          username: ${{ secrets.LINUX_USER }}
          key: ${{ secrets.LINUX_SSH_KEY }}
          script: |
            cd ${{ secrets.LINUX_DIR_PATH }}

            npm install

            npm run build

            cp -f .env.example .env

            composer install --no-interaction --prefer-dist --optimize-autoloader

            php artisan key:generate

            php artisan migrate --force

            php artisan optimize:clear

            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            php artisan db:seed --class=AdminSeeder

            php artisan storage:link

            sudo chown -R www-data:www-data storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache


      - name: => Server Restart
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.LINUX_HOST }}
          username: ${{ secrets.LINUX_USER }}
          key: ${{ secrets.LINUX_SSH_KEY }}
          script: |
            cd ${{ secrets.LINUX_DIR_PATH }}

            sudo systemctl restart nginx
